### ISSUE TITLE
Microverse peer-to-peer review

### ISSUE THREAD

**Issue by lexoxo** [EzekielUtshudi/Porfolio-Project#11]

**Comment by lexoxo** [comment]
## The demo is looking very good 👍🏾. I really liked the opacity of the nav bar, it's perfect. You can improve the output by doing the following:
- Adding the hamburger button
- Adding a max-width to cards
- Adding padding to elements

**Comment by EzekielUtshudi** [comment]
Thank you, very much for the positive feedback, I will make the changes.
